<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run()
    {
        // Supprimer les anciens livres avant d'insérer
        Book::truncate();

        $books = [
            // Livres existants
            [
                'library_id' => 1,
                'title' => 'Le Petit Prince',
                'author' => 'Antoine de Saint-Exupéry',
                'genre_id' => 16, // Jeunesse
                'isbn' => '978-2070612758',
                'description' => 'Le Petit Prince est une œuvre poétique et philosophique sous l\'apparence d\'un conte pour enfants.',
                'year_of_publication' => '1943-04-06',
                'cover_image' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
                'nb_copy' => 5,
                'nb_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => '1984',
                'author' => 'George Orwell',
                'genre_id' => 1, // Science-Fiction
                'isbn' => '978-0451524935',
                'description' => 'Une dystopie sur un régime totalitaire qui contrôle tous les aspects de la vie des citoyens.',
                'year_of_publication' => '1949-06-08',
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Harry Potter à l\'école des sorciers',
                'author' => 'J.K. Rowling',
                'genre_id' => 6, // Fantasy
                'isbn' => '978-2070584628',
                'description' => 'Le premier tome de la saga qui a enchanté des millions de lecteurs à travers le monde.',
                'year_of_publication' => '1997-06-26',
                'cover_image' => 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?w=400',
                'nb_copy' => 7,
                'nb_available' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Meilleur des Mondes',
                'author' => 'Aldous Huxley',
                'genre_id' => 1, // Science-Fiction
                'isbn' => '978-2081471829',
                'description' => 'Une anticipation dystopique d\'une société de consommation et de bonheur artificiel.',
                'year_of_publication' => '1932-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400',
                'nb_copy' => 4,
                'nb_available' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Les Misérables',
                'author' => 'Victor Hugo',
                'genre_id' => 4, // Classique
                'isbn' => '978-2253004224',
                'description' => 'Un chef-d\'œuvre de la littérature française sur la rédemption et la justice sociale.',
                'year_of_publication' => '1862-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
                'nb_copy' => 6,
                'nb_available' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Seigneur des Anneaux - La Communauté de l\'Anneau',
                'author' => 'J.R.R. Tolkien',
                'genre_id' => 6, // Fantasy
                'isbn' => '978-0618002252',
                'description' => 'L\'épopée de la quête de l\'Anneau unique dans la Terre du Milieu.',
                'year_of_publication' => '1954-07-29',
                'cover_image' => 'https://images.unsplash.com/photo-1533481405265-e9ce0c044abb?w=400',
                'nb_copy' => 4,
                'nb_available' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Crime et Châtiment',
                'author' => 'Fiodor Dostoïevski',
                'genre_id' => 5, // Mystère
                'isbn' => '978-2070417506',
                'description' => 'Un roman psychologique sur un étudiant qui commet un meurtre et ses conséquences.',
                'year_of_publication' => '1866-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'L\'Étranger',
                'author' => 'Albert Camus',
                'genre_id' => 4, // Classique
                'isbn' => '978-2070360024',
                'description' => 'Un roman sur l\'absurdité de l\'existence à travers le personnage de Meursault.',
                'year_of_publication' => '1942-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
                'nb_copy' => 4,
                'nb_available' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Rouge et le Noir',
                'author' => 'Stendhal',
                'genre_id' => 4, // Classique
                'isbn' => '978-2253004248',
                'description' => 'L\'ascension et la chute de Julien Sorel dans la France du XIXe siècle.',
                'year_of_publication' => '1830-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'La Peste',
                'author' => 'Albert Camus',
                'genre_id' => 4, // Classique
                'isbn' => '978-2070360055',
                'description' => 'Une allégorie de la résistance face à l\'absurde à travers une épidémie de peste.',
                'year_of_publication' => '1947-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Nouveaux livres de ta liste
            [
                'library_id' => 1,
                'title' => 'L\'Étrange Destin de Wangrin',
                'author' => 'Amadou Hampâté Bâ',
                'genre_id' => 7, // Roman
                'isbn' => '978-2-264-04542-3',
                'description' => 'Ce roman raconte l\'histoire fascinante de Wangrin, un interprète africain travaillant pour l\'administration coloniale. Grâce à son intelligence et à sa ruse, il parvient souvent à manipuler les situations à son avantage.',
                'year_of_publication' => '1973-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
                'nb_copy' => 2,
                'nb_available' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Les Soleils des Indépendances',
                'author' => 'Ahmadou Kourouma',
                'genre_id' => 7, // Roman
                'isbn' => '978-2-020-36040-5',
                'description' => 'Ce roman emblématique raconte la vie de Fama, un prince déchu vivant après les indépendances africaines.',
                'year_of_publication' => '1968-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Une si longue lettre',
                'author' => 'Mariama Bâ',
                'genre_id' => 7, // Roman
                'isbn' => '978-2-070-40444-9',
                'description' => 'Ce roman prend la forme d\'une longue lettre écrite par Ramatoulaye à son amie Aïssatou.',
                'year_of_publication' => '1979-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
                'nb_copy' => 4,
                'nb_available' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Monde s\'effondre',
                'author' => 'Chinua Achebe',
                'genre_id' => 7, // Roman
                'isbn' => '978-0-385-47454-2',
                'description' => 'Ce roman raconte l\'histoire d\'Okonkwo, un guerrier respecté dans la société igbo du Nigeria.',
                'year_of_publication' => '1958-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
                'nb_copy' => 6,
                'nb_available' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Introduction à l\'Intelligence Artificielle',
                'author' => 'Stuart Russell',
                'genre_id' => 2, // Sciences
                'isbn' => '978-0-134-61099-3',
                'description' => 'Ce livre est une référence incontournable pour comprendre les bases de l\'intelligence artificielle.',
                'year_of_publication' => '2020-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=400',
                'nb_copy' => 5,
                'nb_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Histoire du Royaume d\'Abomey',
                'author' => 'Edna G. Bay',
                'genre_id' => 3, // Histoire
                'isbn' => '978-0-852-55548-5',
                'description' => 'Ce livre retrace l\'histoire du puissant royaume d\'Abomey, situé dans l\'actuel Bénin.',
                'year_of_publication' => '1998-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Psychologie des foules',
                'author' => 'Gustave Le Bon',
                'genre_id' => 9, // Psychologie
                'isbn' => '978-2-130-45678-9',
                'description' => 'Cet ouvrage classique analyse le comportement des individus lorsqu\'ils se trouvent dans une foule.',
                'year_of_publication' => '1895-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
                'nb_copy' => 5,
                'nb_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Ainsi parlait Zarathoustra',
                'author' => 'Friedrich Nietzsche',
                'genre_id' => 10, // Philosophie
                'isbn' => '978-2-070-45678-4',
                'description' => 'Ce livre philosophique raconte les discours du prophète Zarathoustra, personnage imaginé par Nietzsche.',
                'year_of_publication' => '1883-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1518744386442-2d48ac47a7eb?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Mythe de Sisyphe',
                'author' => 'Albert Camus',
                'genre_id' => 10, // Philosophie
                'isbn' => '978-2-070-45679-1',
                'description' => 'Dans cet essai philosophique, Camus réfléchit à la question du sens de la vie.',
                'year_of_publication' => '1942-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400',
                'nb_copy' => 2,
                'nb_available' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Germinal',
                'author' => 'Émile Zola',
                'genre_id' => 7, // Roman
                'isbn' => '978-2-070-45680-7',
                'description' => 'Ce roman raconte la vie difficile des mineurs dans le nord de la France au XIXe siècle.',
                'year_of_publication' => '1885-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Madame Bovary',
                'author' => 'Gustave Flaubert',
                'genre_id' => 7, // Roman
                'isbn' => '978-2-070-45681-4',
                'description' => 'Ce roman raconte l\'histoire d\'Emma Bovary, une jeune femme mariée à un médecin de province.',
                'year_of_publication' => '1857-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1516908400650-cb3135aa8c7c?w=400',
                'nb_copy' => 2,
                'nb_available' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'L\'Assommoir',
                'author' => 'Émile Zola',
                'genre_id' => 7, // Roman
                'isbn' => '978-2-070-45683-8',
                'description' => 'Ce roman raconte l\'histoire de Gervaise, une blanchisseuse vivant dans un quartier populaire de Paris.',
                'year_of_publication' => '1877-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
                'nb_copy' => 3,
                'nb_available' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Père Goriot',
                'author' => 'Honoré de Balzac',
                'genre_id' => 7, // Roman
                'isbn' => '978-2-070-45684-5',
                'description' => 'Ce roman se déroule dans une pension modeste de Paris au début du XIXe siècle.',
                'year_of_publication' => '1835-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400',
                'nb_copy' => 4,
                'nb_available' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Crime de l\'Orient-Express',
                'author' => 'Agatha Christie',
                'genre_id' => 5, // Mystère
                'isbn' => '978-2-702-14250-3',
                'description' => 'Le célèbre détective Hercule Poirot se trouve à bord de l\'Orient-Express, bloqué par la neige.',
                'year_of_publication' => '1934-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1500757810556-5d600d9b737d?w=400',
                'nb_copy' => 5,
                'nb_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Ça',
                'author' => 'Stephen King',
                'genre_id' => 8, // Horreur
                'isbn' => '978-2-266-14352-3',
                'description' => 'Dans la petite ville de Derry, des enfants disparaissent. Un groupe d\'adolescents découvre une entité maléfique.',
                'year_of_publication' => '1986-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=400',
                'nb_copy' => 2,
                'nb_available' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Tour du Monde en 80 Jours',
                'author' => 'Jules Verne',
                'genre_id' => 12, // Voyage
                'isbn' => '978-2-070-36827-7',
                'description' => 'Phileas Fogg parie qu\'il peut faire le tour du monde en quatre-vingts jours.',
                'year_of_publication' => '1872-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400',
                'nb_copy' => 1,
                'nb_available' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'genre_id' => 14, // Programmation
                'isbn' => '978-0-132-35088-4',
                'description' => 'Un guide essentiel pour tout développeur souhaitant écrire du code propre, maintenable et efficace.',
                'year_of_publication' => '2008-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400',
                'nb_copy' => 5,
                'nb_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'genre_id' => 1, // Science-Fiction
                'isbn' => '978-2-266-21092-8',
                'description' => 'Sur la planète désertique Arrakis, les intrigues politiques et religieuses se mêlent.',
                'year_of_publication' => '1965-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400',
                'nb_copy' => 1,
                'nb_available' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Les Trois Mousquetaires',
                'author' => 'Alexandre Dumas',
                'genre_id' => 4, // Classique
                'isbn' => '978-2-070-36680-8',
                'description' => 'Le jeune d\'Artagnan quitte sa Gascogne natale pour rejoindre Paris et devenir mousquetaire.',
                'year_of_publication' => '1844-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400',
                'nb_copy' => 5,
                'nb_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Les Fleurs du Mal',
                'author' => 'Charles Baudelaire',
                'genre_id' => 11, // Poésie
                'isbn' => '978-2-070-41345-8',
                'description' => 'Recueil majeur de la poésie française, Les Fleurs du Mal explore les thèmes de la beauté, de la mort et de l\'amour.',
                'year_of_publication' => '1857-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400',
                'nb_copy' => 4,
                'nb_available' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Le Guide Culinaire',
                'author' => 'Auguste Escoffier',
                'genre_id' => 13, // Cuisine
                'isbn' => '978-2-081-22487-8',
                'description' => 'Le livre de référence de la cuisine française moderne avec plus de 5000 recettes.',
                'year_of_publication' => '1903-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1556911261-6bd341186b2f?w=400',
                'nb_copy' => 4,
                'nb_available' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Histoire de l\'Art',
                'author' => 'Ernst Gombrich',
                'genre_id' => 15, // Art
                'isbn' => '978-2-081-22488-5',
                'description' => 'Une introduction accessible et passionnante à l\'histoire de l\'art occidental.',
                'year_of_publication' => '1950-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400',
                'nb_copy' => 4,
                'nb_available' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Millénium - Les Hommes qui n\'aimaient pas les femmes',
                'author' => 'Stieg Larsson',
                'genre_id' => 17, // Thriller
                'isbn' => '978-2-266-20445-3',
                'description' => 'Un thriller haletant qui a conquis le monde entier.',
                'year_of_publication' => '2005-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
                'nb_copy' => 7,
                'nb_available' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'library_id' => 1,
                'title' => 'Pouvoir illimité',
                'author' => 'Tony Robbins',
                'genre_id' => 18, // Développement personnel
                'isbn' => '978-2-266-24578-4',
                'description' => 'Un guide pratique pour transformer sa vie et atteindre ses objectifs.',
                'year_of_publication' => '1987-01-01',
                'cover_image' => 'https://images.unsplash.com/photo-1474418397713-7ede21d49118?w=400',
                'nb_copy' => 8,
                'nb_available' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }

        $this->command->info('✅ ' . count($books) . ' livres ajoutés avec succès !');
    }
}